### ISSUE TITLE
Setup repo for integrated testing with Jenkins

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/solar#1]
@bqpd @galbramc can we get this repo setup with Jenkins as well?

**Comment by galbramc** [comment]
@bqpd, did I show you how to do this?

**Comment by bqpd** [comment]
Nope, but I can copy another project's repo! @mjburton11 you'll need a `TESTS` file

**Comment by galbramc** [comment]
Ok. Give it a try and let me know if you run into any problems.

**Comment by mjburton11** [comment]
@bqpd, I made a TESTS file and a TESTCONFIG file.  Currently, this requires gassolar to be installed.   That will eventually change

**Comment by bqpd** [comment]
This is triggering but I can't figure out why it's failing...@galbramc, did I configure it wrong?

Everything seems good up to `adding test for 'solar/solar.py'` in https://acdl.mit.edu/csi/job/gpkit_ResearchModel_solar_Push/3/buildnode=macys,optimizer=cvxopt/console

**Comment by galbramc** [comment]
This is the error:
```
python /usr/local/bin//coverage xml '--omit=gpkit/*,gpkit-models/*,venv2_gpkit/*,jenkins_test.py'
No data to report.
```
Looks like we are not getting any coverage information from running
```
echo 'from gpkit.tests.test_repo import test_repo; test_repo(xmloutput=True)'
python /usr/local/bin//coverage run --append --source=. jenkins_test.py
```

**Comment by bqpd** [comment]
Huh! but JUnit is finding them, so they must be hidden in some subdirectory

**Comment by bqpd** [comment]
Wait this is weird; this is using the template, so it's not from some change I made to the build script.

**Comment by bqpd** [comment]
@galbramc, I can't figure out what could be special about this repo that's causing `coverage` but _not_ JUnit to miss the xml file

**Comment by galbramc** [comment]
It looks like covarage is not generating any output that can be converted to an xml file. Is there a test that is actually run? Are we somehow ignoring it resulting in no coverage information? You should be able to run the script on your cmputer and see if you get a coverage.xml file.

**Comment by mjburton11** [comment]
@bqpd I don't know how to do this.  Did you get a chance to try this?

**Comment by bqpd** [comment]
Haven't yet but it's next on my todo after some ESP stuff

**Comment by mjburton11** [comment]
cool

**Comment by bqpd** [comment]
@galbramc I removed coverage tests from gpkit_ResearchModel for now so that tests will work...they weren't finding the covered lines with the current testing framework anyway
