### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/solar#24]
@bqpd looks like this repo is failing tests because Mosek is not installed? Is the mosek server license expired?

**Comment by bqpd** [comment]
@galbramc had some ideas about what was happening, since this only happens on a macys/macys_VM/reynolds

**Comment by mjburton11** [comment]
hmmm interesting

**Comment by galbramc** [comment]
we have a new macys, and I had forgotten to copy over mosek to the new machine. I the license was also out of date on macys_VM. Both should be fixed. 

The test in widows failed because it took longer than 30 min to run, and jenkins is currently configured not to allow ReseachModel test to run longer than 30 min. Is this the behavior you want?

**Comment by bqpd** [comment]
It is now only failing because
  1) matplotlib is not installed
  2) if matplotlib is installed, it complains that the python install is "not a framework" and raises a RuntimeWarning

**Comment by bqpd** [comment]
I'm going to try changing the backend

**Comment by bqpd** [comment]
Yeah @galbramc it looks like it'll work if you add `backend : Agg` to `/Users/jenkins/.matplotlib/matplotlibrc`

**Comment by bqpd** [comment]
@galbramc could we install matplotlib on the system level, like numpy?

**Comment by galbramc** [comment]
matplotlib is now installed on macys at the system level

**Comment by bqpd** [comment]
[Still failing](https://acdl.mit.edu/csi/job/gplibrary_Push_Models/72/buildnode=macys,optimizer=mosek/testReport/junit/gpkit.tests.from_paths/TestFiles/test_gassolar_solar_solar_py_mosek/); it also needs the backend config as noted above.

**Comment by bqpd** [comment]
@galbramc, it's [still failing](https://acdl.mit.edu/csi/job/gplibrary_Push_Models/72/buildnode=macys,optimizer=mosek/testReport/junit/gpkit.tests.from_paths/TestFiles/test_gassolar_solar_solar_py_mosek/); it also needs the backend config as noted above.

**Comment by galbramc** [comment]
I aslo removed --system-site-packages which seemed to be something else that stackoverlow said you needed to do. Hopefully this works on linux... otherwise I have to modify the script depending on the machine.

**Comment by bqpd** [comment]
when I ssh'd in it worked with system-site-packages!

**Comment by bqpd** [comment]
uhoh, macys_VM is now having the backend error...try adding the config to it as well?

**Comment by bqpd** [comment]
@galbramc uhoh, macys_VM is now having the backend error...try adding the config to it as well?

**Comment by bqpd** [comment]
@galbramc and macys is having a linking error I can't reproduce:

```
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/jenkins/workspace/gpkit_ResearchModel_turbofan_Push/buildnode/macys/optimizer/mosek/build_gpkit/expopt.so (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

**Comment by bqpd** [comment]
Yeah, I can't reproduce that even by directly running the jenkins config script as my user.

**Comment by galbramc** [comment]
I updated the matplotlibrc on macys_VM

**Comment by galbramc** [comment]
I don't know what that link error is. Can you find anything on the web?

**Comment by bqpd** [comment]
It's complaining that there's not enough room in the binary :-/ and short of recompiling the binary (which is mskexpopt, not the shared library) we can't fix that.

Now, that said, the linking on the jenkins install has already been done many many times over, so I could rewrite the buildscript to not error when the linking fails, but that seems like a bit of a hack!

**Comment by galbramc** [comment]
I'm confused. So why are you getting this error now and not before?

**Comment by galbramc** [comment]
Where are you even getting that error? I don't see it.

**Comment by bqpd** [comment]
no idea why it's showing up now

**Comment by bqpd** [comment]
it's in
https://acdl.mit.edu/csi/job/gpkit_ResearchModel_SPaircraft_Push/buildnode=macys,optimizer=mosek/640/console
, among others

**Comment by galbramc** [comment]
Is the path too long? We can shorten the path.

**Comment by galbramc** [comment]
gplibrary appears to be passing now

**Comment by bqpd** [comment]
yup! tbh since it's just linking mskexpopt it's actually incorrect to check
it in the mosek build...I'll tweak the build script and see if that fixes it

**Comment by bqpd** [comment]
macys_VM stopped finding cvxopt again, what's going on there? https://acdl.mit.edu/csi/job/gpkit_ResearchModel_turbofan_Push/236/buildnode=macys_VM,optimizer=cvxopt/

I bet this will disappear if I test again...

**Comment by bqpd** [comment]
macys_VM seems to have lost connection to pip, it's just instantly failing: https://acdl.mit.edu/csi/job/gpkit_ResearchModel_turbofan_Push/buildnode=macys_VM,optimizer=mosek/

**Comment by galbramc** [comment]
I can't ping https://pypi.python.org/pypi from macys_VM?!?!

**Comment by galbramc** [comment]
I changed a setting on the VM. Maybe that will help...

**Comment by bqpd** [comment]
weird problem importing something on macys: https://acdl.mit.edu/csi/view/convexengineering/job/gpkit_Push/buildnode=macys,optimizer=mosek/539/console

**Comment by galbramc** [comment]
That one you have to google. I need to head home. Later.

**Comment by bqpd** [comment]
haha, fair dos. Have a good evening!

**Comment by bqpd** [comment]
@galbramc there might be a bug with the matplotlib installed on macys? GPkit_Push has this in its console, an error from within matplotlib

```
Traceback (most recent call last):
  File "/Users/jenkins/workspace/gpkit_Push/buildnode/macys/optimizer/mosek/docs/source/examples/plot_sweep1d.py", line 2, in <module>
    import matplotlib as mpl
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-2.2.2-py2.7-macosx-10.13-x86_64.egg/matplotlib/__init__.py", line 131, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-2.2.2-py2.7-macosx-10.13-x86_64.egg/matplotlib/rcsetup.py", line 29, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-2.2.2-py2.7-macosx-10.13-x86_64.egg/matplotlib/fontconfig_pattern.py", line 28, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

**Comment by bqpd** [comment]
From https://github.com/matplotlib/matplotlib/issues/9344, this seems to be fixed by installing matplotlib 2.02 instead??

**Comment by bqpd** [comment]
in good news, all other tests are passing now.

**Comment by galbramc** [comment]
The fix seems to be don't use any system packages and install everything in virtualenv

**Comment by galbramc** [comment]
I've updated many scripts to do this now, but I might have missed some.

**Comment by bqpd** [comment]
what a waste of bandwidth to re-download them all every time!

**Comment by galbramc** [comment]
they are cached on the machines, only download once. But it needs a connection to check every time, and that seems to be flaky for some reason.

**Comment by bqpd** [comment]
everything's running but gpkit_Push right now...

**Comment by bqpd** [comment]
oh! or it looks like you fixed it?

**Comment by galbramc** [comment]
maybe... thought I'm not sure how...

**Comment by mjburton11** [comment]
Well it seems to be passing now which is great!
