### ISSUE TITLE
I can't have more than 1 propulsor currently

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/solar#29]
@courtin can the next steps be to allow for more than 1 propulsor? It would be really interesting to sweep that parameter and see what happens.  How close are we to merging the QProp model?

**Comment by courtin** [comment]
QProp is ready to go except merge conflicts with  the latest version. Multi propulsor should be very simple; I’ll look at that now

Sent from my iPhone

On Apr 20, 2018, at 11:45 AM, Michael Burton <notifications@github.com<mailto:notifications@github.com>> wrote:


@courtin<https://github.com/courtin> can the next steps be to allow for more than 1 propulsor? It would be really interesting to sweep that parameter and see what happens. How close are we to merging the QProp model?

**Comment by courtin** [comment]
Will be addressed by #30

**Comment by bqpd** [comment]
it looks like this should have been closed by #30
