### ISSUE TITLE
build/passing badge 

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/solar#3]
@bqpd how do I get the build/passing badge to show up in the readme?

**Comment by mjburton11** [comment]
I think I got it working.  I used the Markdown unprotected? Is that the correct one?

**Comment by bqpd** [comment]
Looks good!

**Comment by bqpd** [comment]
oh, wait. take a look at the other repos'; your url has a 5 in it that I feel shouldn't be there...

**Comment by mjburton11** [comment]
Hmm... all of the embedded build links for solar have it in there. @galbramc do you know what might be going on here?

**Comment by bqpd** [comment]
I think `[![Build Status](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_solar_Push/5/badge/icon)](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_solar_Push/5/)` should be `[![Build Status](https://acdl.mit.edu/csi/buildStatus/icon?job=gpkit_ResearchModel_solar_Push)](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_solar_Push/)`

**Comment by mjburton11** [comment]
ok that seemed to work.
